#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 下一阶段攻击目标清单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "基于全面深挖结果，推荐攻击顺序："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🥇 优先级1: VCKV系统（已有2个有效账号）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "URL: http://vps.vnpost.vn/vckv/"
echo ""
echo "已确认账号:"
echo "  1. nvdh:123456 ✅"
echo "  2. vckvdbb:abc123 ✅"
echo ""
echo "攻击策略:"
echo "  - 登录后完整枚举功能"
echo "  - 寻找文件上传/导入功能"
echo "  - 测试SQL注入"
echo "  - 查找未授权访问"
echo "  - JS逆向查找隐藏API"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🥈 优先级2: LUONG系统（多个账号）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "URL: http://vps.vnpost.vn/luong/"
echo ""
echo "待测试账号:"
echo "  1. KVMTTCVP:123"
echo "  2. KVMTNVNV:123"
echo "  3. KVMTLDGD:123"
echo ""
echo "攻击策略:"
echo "  - 批量测试所有账号"
echo "  - 权限差异分析"
echo "  - 寻找管理员功能"
echo "  - 工资数据导出"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🥉 优先级3: COS系统"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "URL: http://vps.vnpost.vn/cos/"
echo ""
echo "已知账号:"
echo "  1. bangnh.vckv:thuNa911 (change_password.asp)"
echo "  2. khanhvm.vckv:123456 (Login.asp)"
echo ""
echo "攻击策略:"
echo "  - ASP老系统，可能漏洞更多"
echo "  - 测试SQL注入（ASP经典漏洞）"
echo "  - 测试文件包含/上传"
echo "  - 查找数据库备份"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 备选: 继续深挖Chamcong"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "剩余4个账号:"
echo "  1. KVMBTCKT:123"
echo "  2. KVMBTCVP:123 ✅ (当前使用)"
echo "  3. KVMTBDVP:123"
echo "  4. KVMTNVKS:123"
echo "  5. KVMTVCGN:234"
echo ""
echo "重点:"
echo "  - 测试不同账号的权限"
echo "  - 寻找管理员账号"
echo "  - 寻找文件上传功能"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 完整渗透工作目录"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
tree -L 2 /workspace/vnpost_mipo/ 2>/dev/null || ls -lR /workspace/vnpost_mipo/
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 建议下一步: 全面攻击VCKV系统！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
